### ISSUE TITLE
MSNoise compute_cc stuck at 99%

### ISSUE THREAD

**Issue by omrivolk** [ROBelgium/MSNoise#114]
Hi all,

Whenever I run compute_cc MSNoise gets stuck at 99%. See this screen shot:
https://www.dropbox.com/s/hz97xxg71p2lr6v/msnoise.png

It's been like that for many hours and it happens every time I run it.

I am running MSNoise on a 40 core Ubuntu machine using mysql. With the command:
`msnoise -t 36 compute_cc &
`
 I see that mysqld is stuck on very high cpu and there is one msonise process running with very low cpu. See this screen shot:
https://www.dropbox.com/s/7m5qtjkeuv3rjfa/top.jpg

Thanks
Omry

**Comment by ThomasLecocq** [comment]
Hi Omry,

What happens when you kill all msnoise instances, reset the CC jobs that are "in progress" and run them serially:

```sh
killall msnoise 
msnoise reset CC
msnoise -v4 compute_cc
```

When does it stop ? Does it stop at all ?

How is your MySQL configured? Did you allow for many concurrent connections?

Thomas

**Comment by omrivolk** [comment]
Hi Thomas,
The previous one didn't stop at all, I killed it after a few days.

Tried running serially, It got stuck again at:
`5802732 CC jobs in the database: 44182 todo, 3081 in progress and 5755469 done
`
I assume the "4" in your comment was a typo
Here is what I got:

```
$ msnoise reset CC
$ msnoise -v compute_cc
2018-08-08 15:39:04 [INFO] *** Starting: Compute CC ***
2018-08-08 15:39:04 [INFO] Will compute ZZ
2018-08-08 15:39:12 [INFO] New CC Job: 2013-09-16 (3081 pairs with 79 stations)
/raid1/ov223/msnoise/local/lib/python2.7/site-packages/obspy/signal/detrend.py:31: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(data.dtype, float):
/raid1/ov223/msnoise/local/lib/python2.7/site-packages/obspy/core/trace.py:2111: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(self.data.dtype, float):

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/raid1/ov223/msnoise/local/lib/python2.7/site-packages/msnoise/s03compute_cc.py", line 249, in main
    responses)
  File "/raid1/ov223/msnoise/local/lib/python2.7/site-packages/msnoise/preprocessing.py", line 60, in preprocess
    stream.merge(method=1, interpolation_samples=3, fill_value=None)
  File "/raid1/ov223/msnoise/local/lib/python2.7/site-packages/obspy/core/stream.py", line 1946, in merge
    interpolation_samples=interpolation_samples)
  File "/raid1/ov223/msnoise/local/lib/python2.7/site-packages/obspy/core/trace.py", line 747, in __add__
    interpolation_samples + 2)
  File "/raid1/ov223/msnoise/local/lib/python2.7/site-packages/numpy/core/function_base.py", line 150, in linspace
    return y.astype(dtype, copy=False)
TypeError: astype() got an unexpected keyword argument 'copy'


```

**Comment by omrivolk** [comment]
Alright, I'll try moving to python3 and see if that's the problem

**Comment by ThomasLecocq** [comment]
what was your numpy version ? I close this issue for now, reopen if the problem still exists.
