### ISSUE TITLE
New prefix handling breaks plugins declaration

### ISSUE THREAD

**Issue by ThomasLecocq** [ROBelgium/MSNoise#123]
Due to #122 , the plugins can't declare their tables in the same way.

E.g.

```sh

msnoise config --set plugins=msnoise_sara
Successfully updated parameter plugins = msnoise_sara

msnoise p sara install
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\msnoise-script.py", line 11, in <module>
    load_entry_point('msnoise', 'console_scripts', 'msnoise')()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2321, in load
    return self.resolve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "d:\pythonforsource\msnoise_stack\msnoise\msnoise\scripts\msnoise.py", line 943, in <module>
    plugin.add_command(ep.load())
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2321, in load
    return self.resolve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "d:\pythonforsource\msnoise_stack\msnoise-sara\msnoise_sara\plugin_definition.py", line 6, in <module>
    from .sara_table_def import SaraConfig, SaraStation
  File "d:\pythonforsource\msnoise_stack\msnoise-sara\msnoise_sara\sara_table_def.py", line 9, in <module>
    from msnoise.msnoise_table_def import PrefixerBase
ImportError: cannot import name 'PrefixerBase'
```

**Comment by ThomasLecocq** [comment]
@XavierBeguin could be important for EOS too, as SARA is a plugin you'll use.
