### ISSUE TITLE
Compute_dtt fails for AC/SC

### ISSUE THREAD

**Issue by Corentin3** [ROBelgium/MSNoise#181]
When running compute_dtt, it fails for AC and SC. The problem is the key at line 200.

This fixes the problem (and see attached):
                        if sta1==sta2:
                          dist = 0
                        else:
                          dist = interstations[pair]

**Comment by echavess** [comment]
Hi Thomas and Corentin, 

I am having problems computing dtt for AC, this is the error I get: 

sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'esterillos_nov17.jobs.ref' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT jobs.ref AS jobs_ref, jobs.day AS jobs_day, jobs.pair AS jobs_pair, jobs.jobtype AS jobs_jobtype, jobs.flag AS jobs_flag, jobs.lastmod AS jobs_lastmod
FROM jobs
WHERE jobs.day >= %(day_1)s AND jobs.day <= %(day_2)s AND jobs.jobtype = %(jobtype_1)s AND jobs.lastmod >= %(lastmod_1)s GROUP BY jobs.day ORDER BY jobs.day]
[parameters: {'day_1': datetime.date(2017, 1, 1), 'day_2': datetime.date(2017, 12, 31), 'jobtype_1': 'DTT', 'lastmod_1': datetime.datetime(2019, 10, 30, 18, 50, 46, 835993)}]
(Background on this error at: http://sqlalche.me/e/2j85)

Any help is appreciated!

**Comment by ThomasLecocq** [comment]
@echavess isn't it a similar cause as the "group by mode" that has changed in the recent mysql/mariadb ? see http://msnoise.org/doc/installation.html?highlight=mariadb#mysql-mariadb-configuration ?

**Comment by echavess** [comment]
weird, my my.cnf, located in /usr/local/etc/my.cnf (Mac) reads like this: 

*GROUP_BY is deactivated. 

[mysqld]
character-set-server=utf8
collation-server=utf8_unicode_ci
 sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by ThomasLecocq** [comment]
could you connect to your mysql server and run

```sh
SELECT @@sql_mode;
``` 
?

**Comment by echavess** [comment]
Yep! Here it is: 

```
MySQL [(none)]> SELECT @@sql_mode;
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)

MySQL [(none)]>
```

**Comment by ThomasLecocq** [comment]
so it doesn't look your MySQL takes your my.cnf into account, because it replies "ONLY_FULL_GROUP_BY" ... :s

**Comment by echavess** [comment]
Yep! I saw that. I don't know why tho.

**Comment by ThomasLecocq** [comment]
did you restard mysqld ?

**Comment by savardge** [comment]
Hi, I'm having the same issue. Everything works until dt/t computation. @echavess did you find a fix?

Here's the output I get:

```
(msnoise) genevieve@genevieve-ThinkPad-T530:/data1/Meager/MSNoise$ msnoise compute_dtt
2020-02-17 03:00:10.414211 msnoise [pid 8058][INFO]: *** Starting: Compute DT/T ***
Traceback (most recent call last):
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'msnoise_meager.jobs.ref' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/genevieve/anaconda3/envs/msnoise/bin/msnoise", line 10, in <module>
    sys.exit(run())
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/msnoise/scripts/msnoise.py", line 1202, in run
    cli(obj={})
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/msnoise/scripts/msnoise.py", line 824, in compute_dtt
    main(loglevel=loglevel)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/msnoise/s06compute_dtt.py", line 165, in main
    interval=datetime.timedelta(days=interval))
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/msnoise/api.py", line 1562, in updated_days_for_dates
    order_by(Job.day).all()
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3233, in all
    return list(self)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3389, in __iter__
    return self._execute_and_instances(context)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3414, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/genevieve/anaconda3/envs/msnoise/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'msnoise_meager.jobs.ref' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT jobs.ref AS jobs_ref, jobs.day AS jobs_day, jobs.pair AS jobs_pair, jobs.jobtype AS jobs_jobtype, jobs.flag AS jobs_flag, jobs.lastmod AS jobs_lastmod 
FROM jobs 
WHERE jobs.day >= %(day_1)s AND jobs.day <= %(day_2)s AND jobs.jobtype = %(jobtype_1)s AND jobs.lastmod >= %(lastmod_1)s GROUP BY jobs.day ORDER BY jobs.day]
[parameters: {'day_1': datetime.date(2019, 7, 7), 'day_2': datetime.date(2019, 10, 22), 'jobtype_1': 'DTT', 'lastmod_1': datetime.datetime(2020, 2, 15, 20, 0, 10, 470419)}]
(Background on this error at: http://sqlalche.me/e/2j85)
```

**Comment by savardge** [comment]
Ah, sorry, I had missed the MySQL configuration step in the installation as described in the docs...

On Ubuntu 18.04, I edited the my.cnf as instructed (located in /etc/myql/) and added the lines at the end:
```
[mysqld]
character-set-server=utf8
collation-server=utf8_unicode_ci
sql_mode="TRADITIONAL,NO_AUTO_CREATE_USER"
```
Then restarted mysql:
`sudo /etc/init.d/mysql restart`

And it fixed it.

**Comment by ThomasLecocq** [comment]
Great you found out! Thanks for reporting anyway, I have to check if this ``sql_mode`` change is doable at runtime...

**Comment by echavess** [comment]
I still have the same issue in Mac OSX. Catalina every time I restart the machine or Mysql. 
I re-installed mysql and msnoise and still get this problem:

```
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'msnoise_sses.jobs.ref' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT jobs.ref AS jobs_ref, jobs.day AS jobs_day, jobs.pair AS jobs_pair, jobs.jobtype AS jobs_jobtype, jobs.flag AS jobs_flag, jobs.lastmod AS jobs_lastmod
FROM jobs
WHERE jobs.day >= %(day_1)s AND jobs.day <= %(day_2)s AND jobs.jobtype = %(jobtype_1)s AND jobs.lastmod >= %(lastmod_1)s GROUP BY jobs.day ORDER BY jobs.day]
[parameters: {'day_1': datetime.date(2017, 1, 1), 'day_2': datetime.date(2017, 12, 31), 'jobtype_1': 'DTT', 'lastmod_1': datetime.datetime(2020, 8, 2, 14, 44, 7, 483859)}]
(Background on this error at: http://sqlalche.me/e/13/2j85)
```

The fix for Linux doesn't work in Mac, which is a frustrating. I found this hack on[ stackoverflow](https://stackoverflow.com/questions/41887460/select-list-is-not-in-group-by-clause-and-contains-nonaggregated-column-inc): 

`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

So I type that on MySQLWorkbench: 

<img width="1435" alt="Screen Shot 2020-08-03 at 14 49 46" src="https://user-images.githubusercontent.com/5248851/89226119-a482c400-d598-11ea-94fa-9eff0d644f31.png">

The problems goes away but I get a new problem: 

```
 ech@Esteban  ~/Work/CentralPacific_repeaters/Data_processing/Noise  msnoise compute_dtt                       1 ↵  10478  14:44:13
/Users/ech/anaconda3/lib/python3.7/site-packages/obspy/signal/headers.py:93: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ], align=True)
2020-08-03 20:51:17.791486 msnoise [pid 2070][INFO]: *** Starting: Compute DT/T ***
2020-08-03 20:51:17.929510 msnoise [pid 2070][INFO]: Loading mov=5 days for filter=01
Traceback (most recent call last):
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1002, in __setitem__
    self._set_with_engine(key, value)
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1033, in _set_with_engine
    loc = self.index._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 75, in pandas._libs.index.IndexEngine.get_loc
TypeError: '[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 23 31 32 33 34 35 36 37
 38 39 40 41 42 43 44 45 46]' is an invalid key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ech/anaconda3/bin/msnoise", line 33, in <module>
    sys.exit(load_entry_point('msnoise==1.6', 'console_scripts', 'msnoise')())
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/scripts/msnoise.py", line 1252, in run
    cli(obj={})
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/scripts/msnoise.py", line 824, in compute_dtt
    main(loglevel=loglevel)
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/msnoise/s06compute_dtt.py", line 231, in main
    df['err'][tmp] = 1.0
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1026, in __setitem__
    self._set_with(key, value)
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 1061, in _set_with
    self.loc[key] = value
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 666, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 617, in _get_setitem_indexer
    return self._convert_to_indexer(key, axis=0, is_setter=True)
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1198, in _convert_to_indexer
    return self._get_listlike_indexer(key, axis, raise_missing=True)[1]
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/Users/ech/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1304, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: '[1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 23, 31, 32, 33, 34, 36, 37, 38, 39, 41, 42, 43, 44, 46] not in index'
```

ideas?
