### ISSUE TITLE
Compute_cc unknown issue

### ISSUE THREAD

**Issue by Corentin3** [ROBelgium/MSNoise#183]
I'm running the -t4 compute_cc using for a pair with ZZ,TT,RR,etc. So it may be related to the rotation (or not...).

Here is the problem:

![image](https://user-images.githubusercontent.com/23356210/61516261-e6c87a00-aa04-11e9-8540-0faec831e478.png)

**Comment by ThomasLecocq** [comment]
so 1 pair, ZZ, RR, TT ? do you have all files/components for this one pair/day ?

**Comment by Corentin3** [comment]
@ThomasLecocq yes I can locate them

**Comment by ThomasLecocq** [comment]
ok, then copy/isolate them in a new folder and:

``` sh
msnoise db init --tech 1
msnoise db execute "insert into filters (ref, low, mwcs_low, high, mwcs_high, rms_threshold, mwcs_wlen, mwcs_step, used) values (1, 0.1, 0.1, 1.0, 1.0, 0.0, 12.0, 4.0, 1)"
msnoise config set components_to_compute="ZZ,RR,TT"

msnoise scan_archive --init --path "D:\LOCATION_OF_THE_FILES" --recursively
msnoise populate --fromDA
msnoise new_jobs --init
msnoise -v compute_cc_rot
```

**Comment by Corentin3** [comment]
Still the same problem:

![image](https://user-images.githubusercontent.com/23356210/63862746-5f7c0800-c9ad-11e9-8f1e-c30fa2408d30.png)

**Comment by Corentin3** [comment]
2019-08-28 13:51:06.545327 msnoise [pid 14884][INFO]: Processing pair: HV.AHUD vs HV.JOKA
2019-08-28 13:51:06.562279 msnoise [pid 14884][DEBUG]: Processing ZZ
2019-08-28 13:51:08.986648 msnoise [pid 14884][DEBUG]: Processing RR
2019-08-28 13:51:08.991607 msnoise [pid 14884][DEBUG]: Rotating streams, making sure they are aligned
Traceback (most recent call last):
  File "c:\users\caudroco\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\caudroco\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\caudroco\Anaconda3\Scripts\msnoise.exe\__main__.py", line 9, in <module>
  File "c:\users\caudroco\anaconda3\lib\site-packages\msnoise\scripts\msnoise.py", line 1186, in run
    cli(obj={})
  File "c:\users\caudroco\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\caudroco\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\caudroco\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\caudroco\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\caudroco\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\caudroco\anaconda3\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\caudroco\anaconda3\lib\site-packages\msnoise\scripts\msnoise.py", line 697, in compute_cc_rot
    main(loglevel=loglevel)
  File "c:\users\caudroco\anaconda3\lib\site-packages\msnoise\s03compute_cc.py", line 305, in main
    t2_novert = make_same_length(t2_novert)
  File "c:\users\caudroco\anaconda3\lib\site-packages\msnoise\api.py", line 1753, in make_same_length
    tr.data.mask = mask
UnboundLocalError: local variable 'mask' referenced before assignment

(base) D:\Kilauea_2018\Test_problem>

**Comment by ThomasLecocq** [comment]
should be OK with https://github.com/ROBelgium/MSNoise/issues/183
