### ISSUE TITLE
need help !

### ISSUE THREAD

**Issue by Plop-obspy** [ROBelgium/MSNoise#196]
Hi ! I am a student, trying to work with msnoise but i have some issue.
On the one hand the function compute_cc, remains blocked at 99%, leaving me 15 jobs "in progress".

I decided to continue despite this, the stack is going well, and when I get to compute_mwcs, I have this error message that appears  :
(base) diaclase.site:/diaclase_1/Stage_M2_Marine> msnoise compute_mwcs
2020-02-19 12:22:54.955935 msnoise [pid 28164][INFO]: *** Starting: Compute MWCS ***
2020-02-19 12:22:57.203406 msnoise [pid 28164][INFO]: There are MWCS jobs for some days to recompute for FR.RUSF3:FR.RUSF6
Traceback (most recent call last):
  File "/u/moana/user/mgros/anaconda2/bin/msnoise", line 10, in <module>
    sys.exit(run())
  File "/u/moana/user/mgros/anaconda2/lib/python2.7/site-packages/msnoise/scripts/msnoise.py", line 1202, in run
    cli(obj={})
  File "/u/moana/user/mgros/anaconda2/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/u/moana/user/mgros/anaconda2/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/u/moana/user/mgros/anaconda2/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/u/moana/user/mgros/anaconda2/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/u/moana/user/mgros/anaconda2/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/u/moana/user/mgros/anaconda2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/u/moana/user/mgros/anaconda2/lib/python2.7/site-packages/msnoise/scripts/msnoise.py", line 778, in compute_mwcs
    main(loglevel=loglevel)
  File "/u/moana/user/mgros/anaconda2/lib/python2.7/site-packages/msnoise/s05compute_mwcs.py", line 164, in main
    cur, ref, f.mwcs_low, f.mwcs_high, goal_sampling_rate, -maxlag, f.mwcs_wlen, f.mwcs_step)
  File "/u/moana/user/mgros/anaconda2/lib/python2.7/site-packages/msnoise/move2obspy.py", line 394, in mwcs
    window_length_samples = np.int(window_length * df)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
(base) diaclase.site:/diaclase_1/Stage_M2_Marine>

I don't understand why, nor what I can do to fix it.
Thank you in advance for your response.

**Comment by ThomasLecocq** [comment]
Hi, did you solve this?

**Comment by Plop-obspy** [comment]
I forgot to fill in mwcs_wlen and mwcs_step in my filter,
so obviously it couldn't work!

for compute_cc which are never validated, I change their status manually.

thank you for your reply



2020-02-20 8:44 UTC+01:00, Thomas Lecocq <notifications@github.com>:
> Hi, did you solve this?
>
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/ROBelgium/MSNoise/issues/196#issuecomment-588695792


-- 
Cordialement,
Gros Marine.

**Comment by ThomasLecocq** [comment]
Marine,

OK thanks for this. I will try to make sure those fields cannot be NULL in the next version.

About the "I"n progress jobs: it means they crashed/never completed. You might, next time, want to try resetting them to "T"odo, then run the command in ``msnoise -v`` verbose mode.

**Comment by Plop-obspy** [comment]
when i try to reset the "I"n progress, it reset all

2020-02-20 15:03 UTC+01:00, Thomas Lecocq <notifications@github.com>:
> Marine,
>
> OK thanks for this. I will try to make sure those fields cannot be NULL in
> the next version.
>
> About the "I"n progress jobs: it means they crashed/never completed. You
> might, next time, want to try resetting them to "T"odo, then run the command
> in ``msnoise -v`` verbose mode.
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/ROBelgium/MSNoise/issues/196#issuecomment-589052638


-- 
Cordialement,
Gros Marine.

**Comment by ThomasLecocq** [comment]
it shouldn't do, if you ``msnoise reset`` it only changes the In progress, if you ``msnoise reset --all`` it resets all

**Comment by Plop-obspy** [comment]
I use the web interface button and all the jobs in "T" odo, including
those which was "D" one



2020-02-20 15:10 UTC+01:00, Thomas Lecocq <notifications@github.com>:
> it shouldn't do, if you ``msnoise reset`` it only changes the In progress,
> if you ``msnoise reset --all`` it resets all
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/ROBelgium/MSNoise/issues/196#issuecomment-589063002


-- 
Cordialement,
Gros Marine.

**Comment by Plop-obspy** [comment]
I use the web interface button and all the jobs are passed in "T" odo,
including those which was "D" one

2020-02-20 15:15 UTC+01:00, gros marine <gros.marine2011@gmail.com>:
> I use the web interface button and all the jobs in "T" odo, including
> those which was "D" one
>
>
>
> 2020-02-20 15:10 UTC+01:00, Thomas Lecocq <notifications@github.com>:
>> it shouldn't do, if you ``msnoise reset`` it only changes the In
>> progress,
>> if you ``msnoise reset --all`` it resets all
>>
>> --
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/ROBelgium/MSNoise/issues/196#issuecomment-589063002
>
>
> --
> Cordialement,
> Gros Marine.
>


-- 
Cordialement,
Gros Marine.
