### ISSUE TITLE
'clean_scipy_cache' is not defined

### ISSUE THREAD

**Issue by asyates** [ROBelgium/MSNoise#223]
Getting this error running compute_cc. Looking at the latest commit to api.py, looks like this function has been commented out and references removed? In which case, the remaining reference on line 1804 was missed?

Seems to work fine when this line is removed.

    Traceback (most recent call last):
      File "/home/yatesal/anaconda3/envs/msnoise/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
        self.run()
      File "/home/yatesal/anaconda3/envs/msnoise/lib/python3.8/multiprocessing/process.py", line 108, in run
        self._target(*self._args, **self._kwargs)
      File "/home/yatesal/anaconda3/envs/msnoise/lib/python3.8/site-packages/msnoise/s03compute_no_rotation.py", line 306, in main
        stream = preprocess(db, stations, comps, goal_day, params, responses)
      File "/home/yatesal/anaconda3/envs/msnoise/lib/python3.8/site-packages/msnoise/preprocessing.py", line 195, in preprocess
        stream[i] = check_and_phase_shift(trace, params.preprocess_taper_length)
      File "/home/yatesal/anaconda3/envs/msnoise/lib/python3.8/site-packages/msnoise/api.py", line 1804, in check_and_phase_shift
        clean_scipy_cache()
    NameError: name 'clean_scipy_cache' is not defined

**Comment by ThomasLecocq** [comment]
indeed, corrected in master https://github.com/ROBelgium/MSNoise/commit/5842b142128032828805d5601af9c9310372af14
