### ISSUE TITLE
compute_cc: unexpected EOF while parsing

### ISSUE THREAD

**Issue by asyates** [ROBelgium/MSNoise#233]
Hey,

Stumbled across an error I haven't encountered before while running compute_cc:

```
yatesal@administ-Latitude-5410:~/msnoise/piton04$ msnoise compute_cc
2021-09-16 13:49:01.283831 msnoise [pid 214089][INFO]: *** Starting: Compute CC ***
Traceback (most recent call last):
  File "/home/yatesal/.local/bin/msnoise", line 8, in <module>
    sys.exit(run())
  File "/home/yatesal/.local/lib/python3.8/site-packages/msnoise/scripts/msnoise.py", line 1473, in run
    cli(obj={})
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yatesal/.local/lib/python3.8/site-packages/msnoise/scripts/msnoise.py", line 711, in compute_cc
    main(loglevel=loglevel)
  File "/home/yatesal/.local/lib/python3.8/site-packages/msnoise/s03compute_no_rotation.py", line 257, in main
    params = get_params(db)
  File "/home/yatesal/.local/lib/python3.8/site-packages/msnoise/api.py", line 291, in get_params
    params[name] = itemtype(get_config(s, name))
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

Going into the code (api.py), and doing print(name) before the command itemtype(get_config(s, name)), line 291, shows it fails when it name = 'qc_rms_frequency_ranges'. Checking the msnoise admin, I can see that this config parameter is not listed for me (nor qc_rms_type, which looks like it should be listed after this commit? https://github.com/ROBelgium/MSNoise/commit/8f8d838b045509d99707407bbe266b55c0a31938).

Am running latest version of msnoise i.e. re-installed at time of writing, so can see the new GUI for the admin!

**Comment by asyates** [comment]
Just to confirm it's related to these config parameters, works fine if I just add the following to the api.py get_params() function (while not using QC functionality anyway).

```
        if name in ('qc_rms_frequency_ranges','qc_rms_type'):
            continue
```

**Comment by ThomasLecocq** [comment]
looks like you have an older version of the database and updated to the latest msnoise master version -- make sure to ``msnoise db upgrade``  when you do this !

**Comment by asyates** [comment]
aaaah yup good point, merci!
