### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy.fftpack._fftpack

### ISSUE THREAD

**Issue by trichter** [ROBelgium/MSNoise#293]
I get the following error when running `msnoise test` with `msnoise=1.63 scipy=1.10.0`

```
(skience23) eule@kiste:~/tmp$ msnoise test
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/skience23/bin/msnoise", line 6, in <module>
    from msnoise.scripts.msnoise import run
  File "/home/eule/anaconda/envs/skience23/lib/python3.10/site-packages/msnoise/scripts/msnoise.py", line 12, in <module>
    from ..api import connect, get_config, update_station, get_logger, get_job_types
  File "/home/eule/anaconda/envs/skience23/lib/python3.10/site-packages/msnoise/api.py", line 31, in <module>
    import scipy.fftpack._fftpack as sff
ModuleNotFoundError: No module named 'scipy.fftpack._fftpack'
```

**Comment by ThomasLecocq** [comment]
yup, for skience we will make use of the master/ or msnoise2 branch, which correct this

**Comment by ThomasLecocq** [comment]
pip uninstall msnoise
pip install http://msnoise.org/master.zip

**Comment by trichter** [comment]
Perfect, you are aware of it.

**Comment by trichter** [comment]
Import is working with msnoise-master.
With

```
pip install git+https://github.com/ROBelgium/MSNoise.git
```

you'll get a correct version number (not 0.0.0).

Some test cases still fail, fyi.


```
======================================================================
ERROR: test_013_s03compute_cc (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 203, in test_013_s03compute_cc
    from ..s03compute_no_rotation import main
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/s03compute_no_rotation.py", line 201, in <module>
    from .move2obspy import myCorr2
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/move2obspy.py", line 9, in <module>
    import scipy.fftpack._fftpack as sff
ModuleNotFoundError: No module named 'scipy.fftpack._fftpack'

======================================================================
ERROR: test_018_recompute_cc (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 256, in test_018_recompute_cc
    self.test_013_s03compute_cc()
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 203, in test_013_s03compute_cc
    from ..s03compute_no_rotation import main
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/s03compute_no_rotation.py", line 201, in <module>
    from .move2obspy import myCorr2
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/move2obspy.py", line 9, in <module>
    import scipy.fftpack._fftpack as sff
ModuleNotFoundError: No module named 'scipy.fftpack._fftpack'

======================================================================
ERROR: test_020_update_config (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 264, in test_020_update_config
    shutil.rmtree("STACKS")
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/shutil.py", line 715, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/shutil.py", line 713, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: 'STACKS'

======================================================================
ERROR: test_021_reprocess_BOTH (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 271, in test_021_reprocess_BOTH
    self.test_013_s03compute_cc()
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 203, in test_013_s03compute_cc
    from ..s03compute_no_rotation import main
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/s03compute_no_rotation.py", line 201, in <module>
    from .move2obspy import myCorr2
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/move2obspy.py", line 9, in <module>
    import scipy.fftpack._fftpack as sff
ModuleNotFoundError: No module named 'scipy.fftpack._fftpack'

======================================================================
ERROR: test_022_check_content (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 301, in test_022_check_content
    tmp1 = read(tmp1)
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/obspy/core/util/decorator.py", line 297, in _map_example_filename
    return func(*args, **kwargs)
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/obspy/core/stream.py", line 208, in read
    st = _generic_reader(pathname_or_url, _read, **kwargs)
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/obspy/core/util/base.py", line 656, in _generic_reader
    raise IOError(2, "No such file or directory", pathname)
FileNotFoundError: [Errno 2] No such file or directory: 'STACKS/01/001_DAYS/ZZ/YA.UV05.00_YA.UV06.00/2010-09-01.MSEED'

======================================================================
ERROR: test_024_mwcs (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 324, in test_024_mwcs
    from ..s05compute_mwcs import main
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/s05compute_mwcs.py", line 76, in <module>
    from .move2obspy import mwcs
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/move2obspy.py", line 9, in <module>
    import scipy.fftpack._fftpack as sff
ModuleNotFoundError: No module named 'scipy.fftpack._fftpack'

======================================================================
ERROR: test_030_instrument_response (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 392, in test_030_instrument_response
    self.test_013_s03compute_cc()
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 203, in test_013_s03compute_cc
    from ..s03compute_no_rotation import main
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/s03compute_no_rotation.py", line 201, in <module>
    from .move2obspy import myCorr2
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/move2obspy.py", line 9, in <module>
    import scipy.fftpack._fftpack as sff
ModuleNotFoundError: No module named 'scipy.fftpack._fftpack'

======================================================================
FAIL: test_014_check_done_jobs (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 219, in test_014_check_done_jobs
    self.failUnlessEqual(jobs[0][1], 'D')
AssertionError: 'T' != 'D'
- T
+ D


======================================================================
FAIL: test_015_check_cc_files (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 241, in test_015_check_cc_files
    self.fail()
AssertionError: None

======================================================================
FAIL: test_019_check_SACS (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 259, in test_019_check_SACS
    self.test_015_check_cc_files(format='SAC')
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 241, in test_015_check_cc_files
    self.fail()
AssertionError: None

======================================================================
FAIL: test_029_create_fake_new_files (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 378, in test_029_create_fake_new_files
    self.failUnlessEqual(jobs[0][0], 3)
AssertionError: 6 != 3

======================================================================
FAIL: test_100_plot_cctfime (msnoise.test.tests.MSNoiseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eule/anaconda/envs/skience23b/lib/python3.10/site-packages/msnoise/test/tests.py", line 421, in test_100_plot_cctfime
    self.assertTrue(os.path.isfile(fn), msg="%s doesn't exist" % fn)
AssertionError: False is not true : ccftime YA.UV05.00-YA.UV06.00-ZZ-f1-m1.png doesn't exist

----------------------------------------------------------------------
Ran 52 tests in 23.843s

FAILED (failures=5, errors=7)
```

**Comment by ThomasLecocq** [comment]
ok thanks, I might have to cherry pick the right changes in the branch to master - job for today or later

**Comment by ThomasLecocq** [comment]
rah, it's just because of the version string comparison that fails:
``if scipy.__version__ < "1.4.0":``

**Comment by ThomasLecocq** [comment]
https://github.com/ROBelgium/MSNoise/commit/89c49846c8383ce59926c7338651f4d9221d1da1

**Comment by trichter** [comment]
:+1: easy to fix

**Comment by ThomasLecocq** [comment]
still considering releasing 2.0 before the school :)

**Comment by sukranperk** [comment]
ı have the same problem 

**when ı do;**

pip install msnoise 
I get the following error 
Traceback (most recent call last):
  File "/home/hp/prog/prog/bin/msnoise", line 6, in <module>
    from msnoise.scripts.msnoise import run
  File "/home/hp/prog/prog/lib/python3.11/site-packages/msnoise/scripts/msnoise.py", line 12, in <module>
    from ..api import connect, get_config, update_station, get_logger, get_job_types
  File "/home/hp/prog/prog/lib/python3.11/site-packages/msnoise/api.py", line 31, in <module>
    import scipy.fftpack._fftpack as sff
ModuleNotFoundError: No module named 'scipy.fftpack._fftpack'

**but when ı do this**
pip install http://msnoise.org/master.zip and write msnoise test
Again I have an error 

home/hp/prog/prog/envs/msnoise/lib/python3.8/site-packages/msnoise/_version.py:153: UserWarning: msnoise could not determine its version number. Make sure it is properly installed. This for example happens when installing from a zip archive of the msnoise repository which is not a supported way of installing msnoise.
  warnings.warn("msnoise could not determine its version number. Make "
/home/hp/prog/prog/envs/msnoise/lib/python3.8/site-packages/msnoise/_version.py:153: UserWarning: msnoise could not determine its version number. Make sure it is properly installed. This for example happens when installing from a zip archive of the msnoise repository which is not a supported way of installing msnoise.
  warnings.warn("msnoise could not determine its version number. Make "
Usage: msnoise [OPTIONS] COMMAND [ARGS]...
Try 'msnoise --help' for help.



What should ı do ?

**Comment by ThomasLecocq** [comment]
please don't re-open closed issues.

as said in numerous other issues/comments , the documentation for the new dev version (which includes the command changes) is available at http://msnoise.org/doc/master.
