### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'times' And scary Test

### ISSUE THREAD

**Issue by AlvicePC** [ROBelgium/MSNoise#339]
Hello, i been trying to run msnoise again. But i update all my conda, i decide to install the master version because reading the github i find that there is a lot o bugs now, and i come here with another one.

i run "msnoise cc compute_cc" and it works, but in the next step of the work flow i run "msnoise cc stack -r" and got it...

Lets STACK !
2024-04-21 15:23:29.359505 msnoise [pid 2199][INFO]: There are STACKS jobs for some days to recompute for JA.TOMA.--:JA.TOMA.--
2024-04-21 15:23:29.364789 msnoise [pid 2199][INFO]: Processing JA.TOMA.--:JA.TOMA.---ZZ-1
Traceback (most recent call last):
  File "/home/alvaro/anaconda3/bin/msnoise", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/msnoise/scripts/msnoise.py", line 1529, in run
    cli(obj={})
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/msnoise/scripts/msnoise.py", line 877, in cc_stack
    main('ref', loglevel=loglevel)
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/msnoise/s04_stack2.py", line 167, in main
    _ = dr.where(dr.times >= start, drop=True)
                 ^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'times'

Plus i run "msnoise utils test" and it scared me... please help me. 
[bugreport.txt](https://github.com/ROBelgium/MSNoise/files/15052536/bugreport.txt)

**Comment by AlvicePC** [comment]
Hi, i delete the foldet STACKS, run "msnoise reset STACK --all" ok, run "msnoise cc stack -m" and got it...
Lets STACK !
2024-04-22 16:56:30.475124 msnoise [pid 2286][INFO]: There are STACKS jobs for some days to recompute for JA.CIHU.--:JA.YELA.--
2024-04-22 16:56:30.481280 msnoise [pid 2286][INFO]: Processing JA.CIHU.--:JA.YELA.---ZZ-1
Traceback (most recent call last):
  File "/home/alvaro/anaconda3/bin/msnoise", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/msnoise/scripts/msnoise.py", line 1529, in run
    cli(obj={})
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/msnoise/scripts/msnoise.py", line 879, in cc_stack
    main('mov', loglevel=loglevel)
  File "/home/alvaro/anaconda3/lib/python3.11/site-packages/msnoise/s04_stack2.py", line 173, in main
    dr = dr.resample(times="%is" % params.corr_duration).mean()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NDFrame.resample() got an unexpected keyword argument 'times'

**Comment by ThomasLecocq** [comment]
Do you have the CROSS_CORRELATIONS folder with some ccfs in there?

**Comment by AlvicePC** [comment]
no because i have "keep all = N"

**Comment by ThomasLecocq** [comment]
For the dev version it is compulsory to have keep_all=Y , which is default now

**Comment by AlvicePC** [comment]
ok, i did it, compute cc is ok, it created de CROSS_CORRELATIONS folder then i run "msnoise cc stack -m" and got it.

2024-04-23 02:40:38.554162 msnoise [pid 47575][INFO]: There are STACKS jobs for some days to recompute for JA.ESSJ.--:JA.YELJA.--
2024-04-23 02:40:38.558498 msnoise [pid 47575][INFO]: Processing JA.ESSJ.--:JA.YELJA.---ZZ-1
Killed
