### ISSUE TITLE
Scipy boxcar when using PWS

### ISSUE THREAD

**Issue by ThomasLecocq** [ROBelgium/MSNoise#356]
### Discussed in https://github.com/ROBelgium/MSNoise/discussions/355

<div type='discussions-op-text'>

<sup>Originally posted by **zibiwilczynski** July 26, 2024</sup>
Hi, 

I am using the Master version. When running `msnoise cc compute_cc`, after the correlation was successfull and the CCFs were saved (`keep_all=Y` and `keep_days=Y`), I got an error: 
```
Traceback (most recent call last):
  File "/home/user/miniconda3/bin/msnoise", line 8, in <module>
    sys.exit(run())
  File "/home/user/miniconda3/lib/python3.10/site-packages/msnoise/scripts/msnoise.py", line 1536, in run
    cli(obj={})
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/miniconda3/lib/python3.10/site-packages/msnoise/scripts/msnoise.py", line 767, in cc_compute_cc
    main(loglevel=loglevel)
  File "/home/user/miniconda3/lib/python3.10/site-packages/msnoise/s03compute_no_rotation.py", line 632, in main
    corr = stack(corrs, params.stack_method, params.pws_timegate,
  File "/home/user/miniconda3/lib/python3.10/site-packages/msnoise/api.py", line 1352, in stack
    coh = np.convolve(ss.boxcar(timegate_samples) /
AttributeError: module 'scipy.signal' has no attribute 'boxcar'
``` 
I requested the PWS stack, and the code uses the scipy boxcar function, but it seems the `boxcar()` function is now a part of `scipy.signal.windows` instead of `scipy.signal`. I changed the import function in `msnoise.api` to `import scipy.signal.windows as ss` and it went through correctly. 

Regards
Zibi

</div>

**Comment by ThomasLecocq** [comment]
thanks for reporting, !

**Comment by ThomasLecocq** [comment]
fixed by https://github.com/ROBelgium/MSNoise/commit/9a67c559c5aa322d3d7aea6657f49e5e4e57cab2 ! Thanks!
