### ISSUE TITLE
problem with scan archive

### ISSUE THREAD

**Issue by imme-w** [ROBelgium/MSNoise#373]
Hi, I'm trying to execute the command `msnoise -t 2 scan_archive --init` to scan all my data for the first time.
However, I get this error:

```
2024-10-17 08:43:58.933418 msnoise [pid 2059044][INFO]: *** Starting: Scan Archive ***
2024-10-17 08:43:58.935773 msnoise [pid 2059044][INFO]: Will work on 2 thread(s)
2024-10-17 08:43:58.935820 msnoise [pid 2059044][INFO]: Initializing: updating availability using the whole archive (should be run only once)
2024-10-17 08:43:58.957091 msnoise [pid 2059044][INFO]: Will search for files between 2021-01-01 and 2021-01-10.
Traceback (most recent call last):
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: stations.used_location_codes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wienki/anaconda3/bin/msnoise", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/msnoise/scripts/msnoise.py", line 1529, in run
    cli(obj={})
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/msnoise/scripts/msnoise.py", line 672, in scan_archive
    s01scan_archive.main(init, nthreads, crondays)
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/msnoise/s01scan_archive.py", line 627, in main
    folders_to_glob = get_archives_folders(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/msnoise/s01scan_archive.py", line 341, in get_archives_folders
    for sta in stations:
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2901, in __iter__
    result = self._iter()
             ^^^^^^^^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/wienki/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: stations.used_location_codes
[SQL: SELECT stations.ref AS stations_ref, stations.net AS stations_net, stations.sta AS stations_sta, stations.used_location_codes AS stations_used_location_codes, stations.used_channel_names AS stations_used_channel_names, stations."X" AS "stations_X", stations."Y" AS "stations_Y", stations.altitude AS stations_altitude, stations.coordinates AS stations_coordinates, stations.used AS stations_used
FROM stations
WHERE stations.used = 1 ORDER BY stations.net, stations.sta]
```
What can I do?
Thanks a lot!
Imme

**Comment by ThomasLecocq** [comment]
Hey, it looks like you're using a new version of the code on an old database. Create a new folder & rerun ``msnoise db init``

**Comment by imme-w** [comment]
You were right, that fixed it! Thanks!
