### ISSUE TITLE
Error with compute_cc_rot

### ISSUE THREAD

**Issue by himansh78** [ROBelgium/MSNoise#377]
Hi,
 The code works well with compute_cc for computing ZZ,ZE,ZN...etc. But when I try computing ZZ,ZR,RT... using `msnoise -t 12 cc compute_cc_rot` , I get the following error:

```
(msnoise3) s2122917@braid:~/Documents/agrawal/msnoise3$ 2024-10-28 18:10:18.417837 msnoise [pid 100854][INFO]: New CC Job: 2018-09-06 (1 pairs with 2 stations)
Process Process-9:
Traceback (most recent call last):
  File "/scratch/s2122917/.conda/envs/msnoise3/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/scratch/s2122917/.conda/envs/msnoise3/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/s2122917/.conda/envs/msnoise3/lib/python3.12/site-packages/msnoise-1.6.1.post0+245.g3af55634e2.robelgium.master-py3.12.egg/msnoise/s03compute_cc.py", line 233, in main
    stream = preprocess(db, stations, comps, goal_day, params, responses)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/s2122917/.conda/envs/msnoise3/lib/python3.12/site-packages/msnoise-1.6.1.post0+245.g3af55634e2.robelgium.master-py3.12.egg/msnoise/preprocessing.py", line 90, in preprocess
    logger = get_logger('msnoise.compute_cc_norot_child', loglevel,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/s2122917/.conda/envs/msnoise3/lib/python3.12/site-packages/msnoise-1.6.1.post0+245.g3af55634e2.robelgium.master-py3.12.egg/msnoise/api.py", line 60, in get_logger
    StreamHandler(sys.stdout, format_string=log_fmt,
  File "/scratch/s2122917/.conda/envs/msnoise3/lib/python3.12/site-packages/logbook/handlers.py", line 562, in __init__
    Handler.__init__(self, level, filter, bubble)
  File "/scratch/s2122917/.conda/envs/msnoise3/lib/python3.12/site-packages/logbook/handlers.py", line 192, in __init__
    self.level = lookup_level(level)
                 ^^^^^^^^^^^^^^^^^^^
  File "/scratch/s2122917/.conda/envs/msnoise3/lib/python3.12/site-packages/logbook/base.py", line 167, in lookup_level
    return _reverse_level_names[level]
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^
TypeError: unhashable type: 'Inventory'

```

Notes:
1. remove_response parameter is 'Y' and It works okay with compute_cc.
2. Stations table is populated with latitudes and longitudes.
3. Parameters components_to_compute is updated to include ZZ,ZR,RT,...
4. When I force loglevel to be a string object (instead of inventory), it takes stations as a 'filer' object. It seems the inventory object is not attached correctly. Any possible reasons?

Thanks,
Himanshu

**Comment by ThomasLecocq** [comment]
oopff, sorry, that part of the code has probably not followed all the updates. Are you using the 1.6.x version or the development version ?

If you need the ZZ,RR,TT for tomorgraphic purposes, let me know, I planned to put an example on how to compute it from the other components' tensor (so first: compute_cc with all tensor, and then a small "manual" step to obtain the RR,TT values.
