### ISSUE TITLE
compute_cc problem in merging traces

### ISSUE THREAD

**Issue by ThomasLecocq** [ROBelgium/MSNoise#51]
this should never happen:

```
2015-04-02 15:22:48 [INFO] *** Starting: Compute CC ***
2015-04-02 15:22:48 [INFO] Will compute ZZ
2015-04-02 15:22:48 [INFO] New CC Job: 2006-01-25 (1 pairs with 2 stations)
2015-04-02 15:22:55 [INFO] Pre-Whitening Traces
2015-04-02 15:22:56 [INFO] Processing CC
2015-04-02 15:22:56 [INFO] Job Finished. It took 7.45 seconds
2015-04-02 15:22:56 [INFO] New CC Job: 2006-01-26 (1 pairs with 2 stations)
2015-04-02 15:23:03 [INFO] Pre-Whitening Traces
2015-04-02 15:23:03 [INFO] Processing CC
2015-04-02 15:23:03 [INFO] Job Finished. It took 7.37 seconds
2015-04-02 15:23:03 [INFO] New CC Job: 2006-01-27 (1 pairs with 2 stations)
2015-04-02 15:23:10 [INFO] Pre-Whitening Traces
2015-04-02 15:23:11 [INFO] Processing CC
2015-04-02 15:23:11 [INFO] Job Finished. It took 7.30 seconds
2015-04-02 15:23:11 [INFO] New CC Job: 2006-01-28 (1 pairs with 2 stations)
Traceback (most recent call last):
  File "/home/silvio/anaconda/bin/msnoise", line 9, in <module>
    load_entry_point('msnoise==1.3.1', 'console_scripts', 'msnoise')()
  File "/home/silvio/anaconda/lib/python2.7/site-packages/msnoise/scripts/msnoise.py", line 393, in run
    cli(obj={})
  File "/home/silvio/anaconda/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/silvio/anaconda/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/silvio/anaconda/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/silvio/anaconda/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/silvio/anaconda/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/silvio/anaconda/lib/python2.7/site-packages/msnoise/scripts/msnoise.py", line 174, in compute_cc
    main()
  File "/home/silvio/anaconda/lib/python2.7/site-packages/msnoise/s03compute_cc.py", line 271, in main
    basetime, tramef_Z = preprocess(db, stations, comps, goal_day, params, tramef_Z)
  File "/home/silvio/anaconda/lib/python2.7/site-packages/msnoise/s03compute_cc.py", line 130, in preprocess
    stream[gap[0]] = stream[gap[0]].__add__(stream[gap[1]], method=0, fill_value="interpolate")
  File "/home/silvio/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-linux-x86_64.egg/obspy/core/trace.py", line 681, in __add__
    raise TypeError("Sampling rate differs")
TypeError: Sampling rate differs
```

**Comment by ThomasLecocq** [comment]
Brainstorming the issue:

- we could prevent MSNoise from adding (scanning) files that have a sampling_rate lower than the `cc_sampling_rate`
- at `compute_cc` step, the data could be discarded.

This said, you should never have traces with different sampling rate with the same seed id, e.g. "VG.LOK..HHZ" should always contain the same sampling rate (at least during one day, I suppose). Actually, there could be an issue in MSNoise now that I write these lines: if two separate files are, e.g. BHZ and HHZ, MSNoise will try to read both files and merge them. It's a baaaad idea !

I'll add this response to the issue mentionned above and find a solution for next release !

**Comment by ThomasLecocq** [comment]
I have added a check at `scan_archive` step: streams with `sampling_rate` smaller than `goal_sampling_rate` are not inserted in the database.

**Comment by ThomasLecocq** [comment]
this doesn't prevent 1.4 to be released

**Comment by ThomasLecocq** [comment]
corrected by https://github.com/ROBelgium/MSNoise/commit/6c706c77fd10dc22665708953287ceee5ec6407e
