### ISSUE TITLE
Problem with stack

### ISSUE THREAD

**Issue by echavess** [ROBelgium/MSNoise#60]
[41] ∰ msnoise stack -r -m -i 100
Lets STACK !
/Users/ech/github/obspy/obspy/__init__.py:150: ObsPyDeprecationWarning: Module 'obspy.sac' is deprecated and will stop working with the next ObsPy version. Please import module 'obspy.io.sac' instead.
  ObsPyDeprecationWarning)
/Users/ech/github/obspy/obspy/core/util/deprecation_helpers.py:55: ObsPyDeprecationWarning: Function 'obspy.core.util.gps2DistAzimuth' is deprecated and will stop working with the next ObsPy version. Please use 'obspy.geodetics.gps2dist_azimuth' instead.
  ObsPyDeprecationWarning)
2015-10-14 12:28:11 [DEBUG] Starting the ref stack
2015-10-14 12:28:11 [DEBUG] Processing YZ_INDI:YZ_LAFE-ZZ-1
2015-10-14 12:28:11 [DEBUG] Found 057 updated days
2015-10-14 12:28:11 [DEBUG] New Data for YZ_INDI:YZ_LAFE-ZZ-1
2015-10-14 12:28:11 [DEBUG] Processing YZ_INDI:YZ_SAJU-ZZ-1
2015-10-14 12:28:11 [DEBUG] Found 057 updated days
2015-10-14 12:28:11 [DEBUG] New Data for YZ_INDI:YZ_SAJU-ZZ-1
2015-10-14 12:28:11 [DEBUG] Processing YZ_LAFE:YZ_SAJU-ZZ-1
2015-10-14 12:28:11 [DEBUG] Found 057 updated days
2015-10-14 12:28:11 [DEBUG] New Data for YZ_LAFE:YZ_SAJU-ZZ-1
2015-10-14 12:28:12 [DEBUG] Starting the step stack
Traceback (most recent call last):
  File "/Users/ech/anaconda/bin/msnoise", line 9, in <module>
    load_entry_point('msnoise==1.3', 'console_scripts', 'msnoise')()
  File "/Users/ech/anaconda/lib/python2.7/site-packages/msnoise-1.3-py2.7.egg/msnoise/scripts/msnoise.py", line 392, in run
    cli(obj={})
  File "/Users/ech/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ech/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Users/ech/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ech/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ech/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/Users/ech/anaconda/lib/python2.7/site-packages/msnoise-1.3-py2.7.egg/msnoise/scripts/msnoise.py", line 191, in stack
    main('step', interval)
  File "/Users/ech/anaconda/lib/python2.7/site-packages/msnoise-1.3-py2.7.egg/msnoise/s04stack.py", line 117, in main
    mov_stacks = [int(mi) for mi in mov_stack.split(',')]
ValueError: invalid literal for int() with base 10: ''

**Comment by echavess** [comment]
if using just one value for MWCS, e.g. 30 days, the program runs. Can't split for 2 or more values.

**Comment by ThomasLecocq** [comment]
what were the values you have set there ? numbers or something else ?

**Comment by echavess** [comment]
20,30,40,50

**Comment by echavess** [comment]
As I always do...

**Comment by ThomasLecocq** [comment]
> 2015-10-14 12:28:12 [DEBUG] Starting the step stack

Actually, it should not occur!! Because you asked for a `-m` mov stack...

**Comment by echavess** [comment]
I know. It didn't split the input line: mov_stacks = [int(mi) for mi in mov_stack.split(',')]
Individual values/numbers work though.

**Comment by ThomasLecocq** [comment]
Yeah, that is indeed an issue... but I don't get how the -m goes to STEP stacking... it should not.

can you paste the output of  `msnoise info` ?

**Comment by echavess** [comment]
[13] ☢ msnoise info
/Users/ech/github/obspy/obspy/__init__.py:150: ObsPyDeprecationWarning: Module 'obspy.sac' is deprecated and will stop working with the next ObsPy version. Please import module 'obspy.io.sac' instead.
  ObsPyDeprecationWarning)
/Users/ech/github/obspy/obspy/core/util/deprecation_helpers.py:55: ObsPyDeprecationWarning: Function 'obspy.core.util.gps2DistAzimuth' is deprecated and will stop working with the next ObsPy version. Please use 'obspy.geodetics.gps2dist_azimuth' instead.
  ObsPyDeprecationWarning)

General:
 - db.ini is present


Configuration:
 - /Users/ech/sismo/MSNoise/Nicoya exists
 - CROSS_CORRELATIONS does not exists (and that is normal because keep_all=False)

Raw config bits: "D"efault or "M"odified (green)
 M data_folder: /Users/ech/sismo/MSNoise/Nicoya
 D output_folder: CROSS_CORRELATIONS
 M data_structure: BUD
 D network: *
 D channels: *
 M startdate: 2012-01-01
 D enddate: 2100-01-01
 D analysis_duration: 86400
 D cc_sampling_rate: 20.0
 D resampling_method: Resample
 D decimation_factor: 5
 D preprocess_lowpass: 8.0
 D preprocess_highpass: 0.01
 M maxlag: 60
 D corr_duration: 1800.
 D overlap: 0.0
 D windsorizing: 3
 D crondays: -1
 D ZZ: Y
 D ZR: N
 D ZT: N
 D RZ: N
 D RR: N
 D RT: N
 D TZ: N
 D TR: N
 D TT: N
 D autocorr: N
 D PAZ: N
 D keep_all: N
 D keep_days: Y
 M ref_begin: 2012-01-01
 M ref_end: 2012-09-04
 M mov_stack: 30
 D export_format: MSEED
 D sac_format: doublets
 D dtt_lag: static
 D dtt_v: 1.0
 M dtt_minlag: 10
 M dtt_width: 30
 D dtt_sides: both
 D dtt_mincoh: 0.65
 D dtt_maxerr: 0.1
 D dtt_maxdt: 0.1
CC Jobs:
 D : 2818
 I : 13

DTT Jobs:
 D : 3261

**Comment by ThomasLecocq** [comment]
and that one works, right ?

**Comment by echavess** [comment]
Humm. Python issue here. I just updated anaconda and it seems to be working using multiple moving windows.

**Comment by ThomasLecocq** [comment]
wow... amazing then...

**Comment by echavess** [comment]
Closing?

**Comment by ThomasLecocq** [comment]
if you confirm you successfully have a MOV stack and not a STEP stack, yes.

**Comment by echavess** [comment]
Confirmed: I am using MOV stack and it is rolling!

**Comment by ThomasLecocq** [comment]
CASE CLOSED !
