### ISSUE TITLE
msnoise scan_archive fail

### ISSUE THREAD

**Issue by ashtonflinders** [ROBelgium/MSNoise#74]
First time trying to update with new data (had already done an initialization) w/ sqlite database,
msnoise scan_archive

scan_archive  
2016-10-11 13:48:26 [INFO] **\* Starting: Scan Archive ***
2016-10-11 13:48:26 [INFO] Will work on 1 threads
# % ADDED THIS PRINT STATEMENT

b'data/NC/MCB/MCB.NC..HHZ.2016.281\ndata/NC/MCB/MCB.NC..HHZ.2016.282\ndata/NC/MCB/MCB.NC..HHZ.2016.283\ndata/NC/MCB/MCB.NC..HHZ.2016.284\n'
# %

Traceback (most recent call last):
  File "/usr/local/bin/msnoise", line 9, in <module>
    load_entry_point('msnoise==1.4.1', 'console_scripts', 'msnoise')()
  File "/usr/local/lib/python3.5/dist-packages/msnoise-1.4.1-py3.5.egg/msnoise/scripts/msnoise.py", line 681, in run
    cli(obj={})
  File "/home/ashton/.local/lib/python3.5/site-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/home/ashton/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/ashton/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ashton/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/home/ashton/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(_args, *_kwargs)
  File "/home/ashton/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, *_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/msnoise-1.4.1-py3.5.egg/msnoise/scripts/msnoise.py", line 325, in scan_archive
    main(init, threads=ctx.obj['MSNOISE_threads'])
  File "/usr/local/lib/python3.5/dist-packages/msnoise-1.4.1-py3.5.egg/msnoise/s01scan_archive.py", line 182, in main
    files = sorted(stdout.replace('\r', '').split('\n'))
TypeError: a bytes-like object is required, not 'str'

Looks like the file list is returned as bytes type object and needs to be recast as a string before being converted into a list. From what I remember this was a change in subprocess (?). 

So in, s01scan_archive.py
Ln 181, change;

``` python
                if len(stdout) != 0:
                    files = sorted(stdout.replace('\r', '').split('\n'))
```

to;

``` python
                if len(stdout) != 0:
                    if type(stdout) is not str:
                        stdout = stdout.decode("utf-8")
                        files=[]
                        [files.append(file.split('/')[-1]) for file in stdout.split('\n')]
                        files=sorted(files) 
                    else:
                        files = sorted(stdout.replace('\r', '').split('\n'))
```

This was using the BUD directory structure, and since the find mtime returned the relative path into the BUD data directory (e.g. 'data/NETWORK/STA/file) it was necessary to parse just the file name out so that we didnt end up with a data/NETWORK/STA/data/NETWORK/STA/file, when the folder was later prepended.

**Comment by ThomasLecocq** [comment]
Hi Ashton,

I never used MSNoise for routine on cron job (i.e. without the --init mode), it looks like this mode fails on Python 3.x . It's actually not tested by the continuous integration tools. Thanks for reporting it.

This said, for your case, it looks like you could simply run the --init mode and get it to work.

**Comment by ThomasLecocq** [comment]
should be corrected in https://github.com/ROBelgium/MSNoise/commit/cb564021e6621f3ee19c591623465281fa472a58
