### ISSUE TITLE
Compute_cc terminated with UnboundLocalError

### ISSUE THREAD

**Issue by seismemily** [ROBelgium/MSNoise#96]
When computing CCs and there is no data for a day, instead of skipping over the day, the compute_cc process stops. 

I am trying to compute TT, using BHN and BHE components. For a given day and one station in the pair, there is no BHN file (BHE and BHZ are still present). The other station in the pair does have both BHE and BHN data. msnoise new_jobs has still identified a job to compute here, but it cannot be done. Instead of skipping this date, it shuts down the compute_cc process. 

I've copied the terminal output below. I've also attached my .sac files for a day where there is a component missing in my station pair.

cops-0xxxxx:bass_test r01ec15$ msnoise compute_cc
2017-09-06 17:53:52 [INFO] *** Starting: Compute CC ***
2017-09-06 17:53:52 [INFO] Will compute TT
2017-09-06 17:53:52 [INFO] New CC Job: 2011-09-26 (1 pairs with 2 stations)
2017-09-06 17:53:52 [DEBUG] BA.BA04.E Reading 2 Files
2017-09-06 17:53:52 [DEBUG] Checking sample alignment
2017-09-06 17:53:52 [DEBUG] Checking Gaps
2017-09-06 17:53:52 [DEBUG] BA.BA04.E Highpass at 0.03 Hz
2017-09-06 17:53:52 [DEBUG] BA.BA04.N Reading 2 Files
2017-09-06 17:53:52 [DEBUG] Checking sample alignment
2017-09-06 17:53:52 [DEBUG] Checking Gaps
2017-09-06 17:53:52 [DEBUG] BA.BA04.N Highpass at 0.03 Hz
2017-09-06 17:53:52 [DEBUG] BA.BA06.E Reading 2 Files
2017-09-06 17:53:52 [DEBUG] Checking sample alignment
2017-09-06 17:53:52 [DEBUG] Checking Gaps
2017-09-06 17:53:52 [DEBUG] BA.BA06.E Highpass at 0.03 Hz
2017-09-06 17:53:52 [INFO] Processing pair: BA.BA04 vs BA.BA06
2017-09-06 17:53:52 [INFO] Azimuth=75.6
2017-09-06 17:53:52 [DEBUG] Processing TT
2017-09-06 17:53:52 [DEBUG] Rotating streams, making sure they are aligned
Process Process-1:
Traceback (most recent call last):
  File "/Users/r01ec15/anaconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/r01ec15/anaconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/r01ec15/anaconda/lib/python2.7/site-packages/msnoise/s03compute_cc.py", line 318, in main
    t2_novert = make_same_length(t2_novert)
  File "/Users/r01ec15/anaconda/lib/python2.7/site-packages/msnoise/api.py", line 1433, in make_same_length
    tr.data.mask = mask
UnboundLocalError: local variable 'mask' referenced before assignment

Files: [2011_09_06.zip](https://github.com/ROBelgium/MSNoise/files/1283903/2011_09_06.zip)

**Comment by rantanplan77** [comment]
A similar problem if the preprocessing fails:

```
/home/luckyluke/miniconda3/envs/py35/lib/python3.5/site-packages/obspy/core/stream.py:2838: UserWarning: Incompatible traces (sampling_rate, dtype, ...) with same id detected. Doing nothing.
  warnings.warn(msg)
Process Process-1:
Traceback (most recent call last):
  File "/home/luckyluke/miniconda3/envs/py35/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/luckyluke/miniconda3/envs/py35/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/luckyluke/Interferometry/MSNoise/msnoise/s03compute_cc.py", line 249, in main
    responses)
  File "/home/luckyluke/Interferometry/MSNoise/msnoise/preprocessing.py", line 60, in preprocess
    stream.merge(method=1, interpolation_samples=3, fill_value=None)
  File "/home/luckyluke/miniconda3/envs/py35/lib/python3.5/site-packages/obspy/core/stream.py", line 1918, in merge
    self._merge_checks()
  File "/home/luckyluke/miniconda3/envs/py35/lib/python3.5/site-packages/obspy/core/stream.py", line 1856, in _merge_checks
    raise Exception(msg)
Exception: Can't merge traces with same ids but differing sampling rates!
```

Maybe it would be an idea to catch any exception, mark the corresponding job as "Failed" or similar, and moving on to the next job (without) exiting.

**Comment by ThomasLecocq** [comment]
Yeahhhh... the preprocess and mask checking still need some cleaning...

**Comment by omrivolk** [comment]
Same problem here

```
2018-08-27 09:24:54 [INFO] Processing pair: Z7.ADA vs Z7.FAL1
2018-08-27 09:24:54 [INFO] Azimuth=207.2
2018-08-27 09:24:54 [DEBUG] Processing RR
2018-08-27 09:24:54 [DEBUG] Rotating streams, making sure they are aligned
Process Process-16:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/raid1/ov223/env_msnoise_annoying_format/lib/python3.5/site-packages/msnoise/s03compute_cc.py", line 318, in main
    t2_novert = make_same_length(t2_novert)
  File "/raid1/ov223/env_msnoise_annoying_format/lib/python3.5/site-packages/msnoise/api.py", line 1437, in make_same_length
    tr.data.mask = mask
UnboundLocalError: local variable 'mask' referenced before assignment
```

I'm pretty sure this has to do with `st` object haveing a length of 1. That is the only case no covered by the `if else` block just before:

```
if len(st) == 2:
        mask = np.logical_or(st[0].data.mask, st[1].data.mask)
elif len(st) == 3:
        mask = np.logical_or(st[0].data.mask, st[1].data.mask, st[2].data.mask)
```

Does this fix makes sense?

```
if len(st) == 1:
        mask = st[0].data.mask
elif len(st) == 2:
        mask = np.logical_or(st[0].data.mask, st[1].data.mask)
elif len(st) == 3:
        mask = np.logical_or(st[0].data.mask, st[1].data.mask, st[2].data.mask)
```

**Comment by ThomasLecocq** [comment]
@omrivolk actually if there is only one trace in the Stream it should not check for the mask (and gaps)... I guess the check for this should be on the number of unique ids in the Stream...

**Comment by ThomasLecocq** [comment]
done
